# -*- coding: utf-8 -*-
"""21-04-2025 pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pYAV4ddvnr-uAIdw8P3zdW3EgYy0LPjB
"""

import pandas as pd
df=pd.read_csv("/content/Logistic_Iris.csv")
print(df)

df.head(10)

df.head()

df.info()

df.describe()

df.tail()

df.columns

df.dtypes

df.isnull()

df.notnull()

#select specific column from table
df["Sepal Length"]

#for selecting specific row from table
df[:1]

df.iloc[0:5]

df.iloc[5:10:2]

df["new column"]=df["Sepal Length"]+df["Sepal Width"]
print(df.head())

df.drop(['new column'],axis=1)

